# Generated by Django 5.0.3 on 2024-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
