# Generated by Django 5.0.3 on 2024-03-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_prise',
        ),
    ]
