# Generated by Django 5.0.3 on 2024-03-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_item_item_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=5),
        ),
    ]
