# Generated by Django 5.0.3 on 2024-03-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_item_price_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dummy',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='food.item'),
        ),
    ]
