# Generated by Django 5.0.3 on 2024-03-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_profile_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dummy',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='food.item'),
        ),
    ]
