# Generated by Django 5.0.3 on 2024-03-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_profile_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy',
        ),
    ]
