# Generated by Django 5.0.3 on 2024-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
