# Generated by Django 5.0.3 on 2024-04-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
